FROM nginx:alpine

# Copiar index.html a la raíz
COPY web/index.html /usr/share/nginx/html/index.html
# Copiar carpetas completas del frontend
COPY web/html /usr/share/nginx/html/html
COPY web/css /usr/share/nginx/html/css
COPY web/js /usr/share/nginx/html/js

# Copiar configuración de nginx
COPY web/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]