FROM nginx:alpine

# Copiar index.html a la raíz
COPY web/index.html /usr/share/nginx/html/index.html

# Copiar configuración de nginx
COPY web/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]